config/routes.rb
Rails.application.routes.draw do

	root 'dashboard#index'

  devise_for :users do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end

	get '/help' => 'dashboard#help'
		
	resources :users, only: [] do
  	resources :crawlers do
  		get 'crawl'
  	end
  end
  
end

app/models/activity.rb
class Activity < ApplicationRecord

	belongs_to :crawler
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crawler.rb
class Crawler < ApplicationRecord

	belongs_to :user

	has_many :activities

	validates :url, presence: true

	def register_activity!(data)
		activities.create(
			source_name: data[:vendor],
			fields_data_number: data.count
		)
	end

end

app/models/snapdeal_service.rb
require 'open-uri'

class SnapdealService

  def initialize(product_url:)
    @product_url = product_url
    @page = Nokogiri::HTML(open(product_url))
    properties_list
  end

  attr_reader :product_url, :page, :prop_list

  def to_json
    {
      vendor: vendor,
      title: title,
      real_price: int_price,
      offer_price: int_offer_price,
      categories: categories,
      stock: stock,
      image_link: image_link,
      page_link: page_link,
      sku: sku,
      brand: brand,
      material: material,
      color:  colour
    }
  end


  private

    def vendor
      "Snapdeal"
    end

    def title
      page.css('h1')[0].text
    end

    def real_price
      page.css('.pdpCutPrice').text.strip
    end

    def offer_price
      page.css('.payBlkBig').text.strip
    end

    def categories
      categories = []
      page.css("#breadCrumbWrapper a[itemprop=url]").each do |value|
        categories << value.text.strip
      end
      categories.map!(&:strip)
      categories = categories.reject { |c| ['home', 'Home', 'HOME'].include?(c) }
      categories
    end

    def stock
      page.css("div[class='message-alert alert-error soldDiscontAlert']").size == 0 ? 1 : 0
    end

    def image_link
      page.at_css("#bx-slider-left-image-panel img")["src"]
    end

    def page_link
      page.at_css("link[rel='canonical']")['href']
    end

    def sku
      prop_list.fetch("SUPC", "")
    end

    def brand
      brand = prop_list.fetch("Brand", "")
      if brand.present?
        brand.strip
      else
        ''
      end
    end

    def material
      material = prop_list.fetch("Material", "")
      if material.present?
        material.strip
      elsif prop_list.fetch("Primary Material", "").present?
        material = prop_list.fetch("Primary Material")
        material.strip
      else
        ''
      end
    end

    def colour
      colour = prop_list.fetch("Color", "")
      if colour.present?
        colour.strip
      else
        ''
      end
    end

    def int_price
      if real_price.present?
        real_price.split("Rs.")[1].delete(',').squish.to_i
      else
        0
      end
    end

    def int_offer_price
      if offer_price.present?
        offer_price.delete(',').squish.to_i
      else
        0
      end
    end

    def properties_list

      @prop_list ||= Hash.new
      page.css(".dtls-list").css("li").each do |prop|
        props = prop.text.split(":")
        @prop_list[props[0].try("strip")] = props[1].try("strip")
      end

      page.css(".product-spec tr").each do |prop|
        td = prop.css("td")
        if td.size == 2
          @prop_list[td[0].text.try("strip")] = td[1].text.try("strip")
        end
      end
      @prop_list

    end

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :crawlers
  has_many :activities, through: :crawlers
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crawlers_controller.rb
class CrawlersController < ApplicationController

  before_action :authenticate_user!, :load_user
  before_action :set_crawler, only: [:show, :edit, :update, :destroy]
  

  def index
    @crawlers = @user.crawlers
  end

  def show; end

  def new
    @crawler = @user.crawlers.new
  end

  def edit; end

  def create
    @crawler = @user.crawlers.new(crawler_params)

    respond_to do |format|
      if @crawler.save
        format.html { redirect_to user_crawler_url(@user, @crawler), notice: 'Crawler was successfully created.' }
        format.json { render :show, status: :created, location: @crawler }
      else
        format.html { render :new }
        format.json { render json: @crawler.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @crawler.update(crawler_params)
        format.html { redirect_to user_crawler_url(@user, @crawler), notice: 'Crawler was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler }
      else
        format.html { render :edit }
        format.json { render json: @crawler.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @crawler.destroy
    respond_to do |format|
      format.html { redirect_to user_crawlers_url(@user), notice: 'Crawler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def crawl
    @crawler = @user.crawlers.find(params[:crawler_id])
    service = SnapdealService.new(product_url: @crawler.url)
    @result_json = service.to_json
    @result = @crawler.register_activity!(@result_json)
    respond_to do |format|
      format.js { }
    end
  end

  private

    def load_user
      @user = User.find(params[:user_id])
    end

    def set_crawler
      @crawler = @user.crawlers.find(params[:id])
    end

    def crawler_params
      params.require(:crawler).permit(:url)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_action :authenticate_user!


	def index
		@activities = current_user.activities
	end

	def help; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crawlers_helper.rb
module CrawlersHelper
end

app/views/crawlers/_crawl_result.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Data</th>
        <th>Value</th>
      </tr>
    </thead>

    <tbody>
      <% @result_json.each do | key, value | %>
        <tr>
          <td>
            <%= key %>
          </td>
          <td>
            <%= value %>
          </td>
        </tr>
      <% end %>

      <% if false %>
      <tr>
        <td>
          source
        </td>
        <td>
          <%= truncate(result.source_name, length: 10) %>
        </td>
      </tr>
      <tr>
        <td>
          data no.
        </td>
        <td>
          <%= result.fields_data_number %>
        </td>
      </tr>
      <% end %>
      
    </tbody>
  </table>
</div>

app/views/crawlers/_form.html.erb
<%= form_for([@user, crawler]) do |f| %>
  <% if crawler.errors.any? %>
    <div id="error_explanation form-group">
      <h5>
        <%= pluralize(crawler.errors.count, "error") %> 
        prohibited this crawler from being saved:
      </h5>

      <ul>
      <% crawler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= f.submit "save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/crawlers/crawl.js.erb
$('.side-bar-results').html('<%= escape_javascript(render :partial => "crawlers/crawl_result", locals: { result: @result }) %>');

app/views/crawlers/edit.html.erb
<h1>Editing Crawler</h1>

<%= render 'form', crawler: @crawler %>

<%= link_to 'Show', user_crawler_url(@user, @crawler) %> |
<%= link_to 'Back', user_crawlers_path(@user) %>

app/views/crawlers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crawlers</h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Url</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @crawlers.each.with_index(1) do |crawler, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= link_to truncate(crawler.url, length: 80), crawler.url, target: "_blank" %></td>
          <td><%= link_to 'Crawl', user_crawler_crawl_url(@user, crawler), remote: true %></td>
          <td><%= link_to 'Show', user_crawler_url(@user, crawler) %></td>
          <td><%= link_to 'Edit', edit_user_crawler_url(@user, crawler) %></td>
          <td><%= link_to 'Destroy', user_crawler_url(@user, crawler), method: :delete, data: { confirm: 'Are you sure! You want to delete it. This will delete all information related to current resource.' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Crawler', new_user_crawler_url(@user) %>

app/views/crawlers/new.html.erb
<h1>New Crawler</h1>

<%= render 'form', crawler: @crawler %>

<%= link_to 'Back', user_crawlers_url(@user) %>

app/views/crawlers/show.html.erb
<p id="notice" class="text-justify">
	<%= notice %>
</p>

<p class="text-justify">
  <strong>Url:</strong>
</p>
<p class="text-justify">
  <%= link_to @crawler.url, @crawler.url, target: "_blank" %>
</p>

<%= link_to 'Edit', edit_user_crawler_url(@user, @crawler) %> |
<%= link_to 'Back', user_crawlers_url(@user) %> |
<%= link_to 'Crawl', user_crawler_crawl_url(@user, @crawler), remote: true %>

app/views/dashboard/help.html.erb
help

app/views/dashboard/index.html.erb
<p class="text-lg-left">
	<% if current_user %>
		Welcome <%= current_user.email %>
	<% else %>
		Welcome
	<% end %>
</p>

<p class="text-lg-left">your recent activities...</p>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Url</th>
        <th>Crawled At</th>
        <th>resource Count</th>
      </tr>
    </thead>

    <tbody>
    	<% @activities.each do | activity | %>
	      <tr>
	        <td>
	          <%= activity.source_name %>
	        </td>
	        <td>
	          <%= activity.created_at.in_time_zone('Kolkata').strftime("on %d %b %Y, %I:%M%p") %>
	        </td>
	        <td>
	          <%= activity.fields_data_number %>
	        </td>
	      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="free admin dashboard">
    <meta name="author" content="rakesh">
    <link rel="icon" href="../../favicon.ico">

    <title>Admin Dashboard</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
      <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dashboard", root_url, class: "navbar-brand" %>
      <div id="navbar">
        <nav class="nav navbar-nav pull-xs-left">
          <%= link_to "Dashboard", root_url, class: "nav-item nav-link" %>
          <% if current_user %>
            <%= link_to "Log Out", destroy_user_session_url, class: "nav-item nav-link" %>
            <%= link_to "Urls ", user_crawlers_url(current_user), class: "nav-item nav-link" %>
          <% else %>
            <%= link_to "Log In", user_session_url, class: "nav-item nav-link" %>
            <%= link_to "Sign Up", new_user_registration_url, class: "nav-item nav-link" %>
         	<% end %>
          
          <%= link_to "Help", '/help', class: "nav-item nav-link" %>
        </nav>
        <form class="pull-xs-right">
          <input type="text" class="form-control" placeholder="Search...">
        </form>
      </div>
    </nav>
    <div class="container-fluid container-top-margin">
	    <div class="row">
	    	<div class="col-sm-3 col-md-2 sidebar side-bar-results">

	    	</div>
	    	<div class="col-sm-9 col-md-10 main">
	    		<%= yield %>
	    	</div>
	    </div>

	    </div>

  </body>

</html>